<?php

namespace EdcomsCMS\AuthBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * address_hooksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class address_hooksRepository extends EntityRepository
{
}
