<?php

namespace EdcomsCMS\AuthBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * cmsUserDashboardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cmsUserDashboardRepository extends EntityRepository
{
}
