<?php

namespace EdcomsCMS\AuthBundle\Entity;

use Symfony\Component\Security\Core\Exception\AccountStatusException;
use Doctrine\ORM\EntityRepository;

/**
 * cmsUserGroupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cmsUserGroupsRepository extends EntityRepository
{
    public function loadRolesById($id) {
        $roles = $this->getEntityManager('edcoms_cms')
                ->createQuery("SELECT r"
                            . "FROM EdcomsCMSAuthBundle:cmsUserGroups r ")
                ->getResult();
        return $roles;
    }
}
