<?php

namespace EdcomsCMS\AuthBundle\Entity;

/**
 * ConnectorKeyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConnectorKeyRepository extends \Doctrine\ORM\EntityRepository
{
}
