<?php

namespace EdcomsCMS\AuthBundle\Entity;

/**
 * ConnectorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConnectorRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByKeySuffix($key)
    {
        $connector = $this->getEntityManager('edcoms_cms')
            ->createQuery("SELECT c "
                . "FROM EdcomsCMSAuthBundle:Connector c "
                . "LEFT JOIN c.keys ck "
                . "WHERE ck.apiKey LIKE :key")
            ->setParameter('key', '%'.$key)
            ->getResult();

        if (null === $connector) {
            return false;
        }
        return $connector;
    }

    public function findByKeyAndHook($referral, $key)
    {
        $connector = $this->getEntityManager('edcoms_cms')
            ->createQuery("SELECT c FROM EdcomsCMSAuthBundle:Connector c "
                        . "LEFT JOIN c.keys AS ck "
                        . "LEFT JOIN c.hooks AS ch "
                        . "WHERE ck.apiKey=:key AND ch.url=:referral")
            ->setParameters(['key'=>$key, 'referral'=>$referral])
            ->getOneOrNullResult();
        if ($connector) {
            return $connector;
        }
        return false;
    }

    /**
     * Fetches the Connector associated with the ConnectorKey containing the API key of '$apiKey'.
     *
     * @param   string  $apiKey  The API key used as the ConnectorKey fetch criteria.
     *
     * @return  Connector        The found connector, or 'null' if not found.
     */
    public function findByApiKey($apiKey)
    {
        return $this
            ->getEntityManager('edcoms_cms')
            ->createQueryBuilder()
            ->select('c')
            ->from('EdcomsCMSAuthBundle:Connector', 'c')
            ->join('c.keys', 'ck')
            ->where('ck.apiKey = :apikey')
            ->setParameter('apikey', $apiKey)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
