<?php

namespace EdcomsCMS\AuthBundle\Entity;

/**
 * ConnectorHookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConnectorHookRepository extends \Doctrine\ORM\EntityRepository
{
}
