<?php

namespace EdcomsCMS\AuthBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * dashboard_itemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class dashboardItemsRepository extends EntityRepository
{
}
