<?php

namespace EdcomsCMS\ContentBundle\Entity;

use Doctrine\ORM\EntityRepository;
use EdcomsCMS\AuthBundle\Entity\cmsUsers;

/**
 * ActivityLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityLogRepository extends EntityRepository
{

    /**
     * Find log entries by user, action and target.
     * This is grouped by reference ID.
     * The returned array contains the first date and log id of the occurrence of the reference ID
     *
     * @param $user - cmsUser
     * @param $action - string
     * @param $target - string
     * @return array - results from DB query
     */
    public function findDistinct(cmsUsers $user, $action, $target)
    {
        if (!is_string($action)) {
            throw new \InvalidArgumentException('Parameter 2 must be scalar type string');
        }
        if (!is_string($target)) {
            throw new \InvalidArgumentException('Parameter 3 must be scalar type string');
        }

        $logs = $this->getEntityManager('edcoms_cms')
                ->createQuery("SELECT MIN(a.id) AS id, a.referenceID, MIN(a.date) AS date "
                    . "FROM EdcomsCMSContentBundle:ActivityLog a "
                    . "LEFT JOIN a.user u "
                    . "WHERE a.user=:user AND a.action=:action AND a.referenceType=:referenceType "
                    . "GROUP BY a.referenceID "
                    . "ORDER BY date ASC")
                ->setParameter('user', $user)
                ->setParameter('action', $action)
                ->setParameter('referenceType', $target)
                ->getResult();

        return $logs;
    }
}
