<?php

namespace EdcomsCMS\ContentBundle\Entity;

/**
 * ContentMigrationConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentMigrationConfigRepository extends \Doctrine\ORM\EntityRepository
{
}
