<?php

namespace EdcomsCMS\ContentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContentCacheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentCacheRepository extends EntityRepository
{
    public function findByType($type)
    {
        $content = $this->getEntityManager('edcoms_cms')
                ->createQuery("SELECT cc "
                            . "FROM EdcomsCMSContentBundle:ContentCache cc "
                            . "INDEX BY cc.UUID "
                            . "WHERE cc.type=:type")
                ->setParameter('type', $type)
                ->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
        if (null === $content) {
            $message = sprintf(
                'Unable to find an active ContentCache EdcomsCMSContentBundle:ContentCache object identified by "%s".',
                $type
            );
            throw new Exception($message);
        }
        return $content;
    }
}
