<?php

namespace EdcomsCMS\ContentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContentTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentTypeRepository extends EntityRepository
{
    public function findByNotSystem()
    {
        $system = 'System %';
        $contentType = $this->getEntityManager('edcoms_cms')
                ->createQuery("SELECT ct, cf, tf "
                            . "FROM EdcomsCMSContentBundle:ContentType ct "
                            . "LEFT JOIN ct.template_files tf "
                            . "LEFT JOIN ct.custom_fields cf "
                            . "WHERE ct.name NOT LIKE :system")
                ->setParameter('system', $system)
                ->getResult();

        if (null === $contentType) {
            $message = sprintf(
                'Unable to find any non-system Content Types EdcomsCMSContentBundle:ContentType object identified by'
            );
            throw new Exception($message);
        }
        return $contentType;
    }
}
