<?php

namespace EdcomsCMS\ContentBundle\Entity;

use Doctrine\ORM\EntityRepository;
use EdcomsCMS\ContentBundle\Entity\ContentType;

/**
 * CustomFieldsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomFieldsRepository extends EntityRepository
{
    public function findByContentType($contentType)
    {
        $custom_fields = $this->getEntityManager('edcoms_cms')
                ->createQuery("SELECT cf "
                            . "FROM EdcomsCMSContentBundle:CustomFields cf "
                            . "WHERE cf.content_type = :content_type")
                ->setParameter('content_type', $contentType->getId())
                ->getResult();
        $custom_field_key = [];
        foreach ($custom_fields as $custom_field) {
            $custom_field_key[$custom_field->getName()] = $custom_field;
        }
        return $custom_field_key;
    }
    
    /**
     * Returns a collection of CustomFields that belong to '$contentType',
     * where they are constrained as a result of CustomFieldData records referencing them.
     * 
     * @param   ContentType $contentType    Used to search for CustomFields that reference this ContentType.
     * 
     * @return  array                       Collection of found CustomField records.
     */
    public function findConstrainedCustomFieldsByContentType(ContentType $contentType)
    {
        $em = $this->getEntityManager('edcoms_cms');
        $queryBuilder = $em->createQueryBuilder();
        $subQueryBuilder = $em->createQueryBuilder();
        
        $customFields = $queryBuilder
            ->select('cf')
            ->from('EdcomsCMSContentBundle:CustomFields', 'cf')
            ->where(
                $queryBuilder->expr()->in(
                    'cf.id',
                    $subQueryBuilder
                        ->select('cf2.id')
                        ->from('EdcomsCMSContentBundle:CustomFieldData', 'cfd')
                        ->innerJoin('cfd.custom_fields', 'cf2')
                        ->innerJoin('cf2.content_type', 'ct')
                        ->where(
                            $subQueryBuilder->expr()->eq(
                                'ct.id',
                                $contentType->getId()
                            )
                        )
                        ->getDQL()
                )
            )
            ->getQuery()
            ->getResult();
        
        return $customFields;
    }
}
