<?php

namespace EdcomsCMS\ContentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LinkBuilderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkBuilderRepository extends EntityRepository
{
    public function findByFriendlyLink($friendlyLink)
    {
        $linkBuilder = $this
            ->getEntityManager('EdcomsCMSContentBundle:LinkBuilder')
            ->createQuery(
                'SELECT ' .
                    'l, ' .
                    's ' .
                'FROM ' .
                    'EdcomsCMSContentBundle:LinkBuilder l ' .
                    'LEFT JOIN l.structure s ' .
                'WHERE ' .
                    'l.friendlyLink = :link'
            )
            ->setParameter('link', $friendlyLink)
            ->setMaxResults(1)
            ->getResult();

        return empty($linkBuilder) ? null : $linkBuilder[0];
    }
}
