<?php

namespace EdcomsCMS\ContentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SearchPhrasesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchPhrasesRepository extends EntityRepository
{
    public function findByTerm($term)
    {
        $terms = $this->getEntityManager('edcoms_cms')
                ->createQuery("SELECT sp "
                            . "FROM EdcomsCMSContentBundle:SearchPhrases sp "
                            . "WHERE sp.phrase LIKE :term")
                ->setParameter('term', '%'.$term.'%')
                ->getResult();
        if ($terms === null) {
            return false;
        }
        return $terms;
    }
}
