security:
    access_control:
        - { path: ^/cms, roles: [ROLE_CMS_USERS, ROLE_CMS_ADMIN] }
        - { path: ^/cms/users, roles: ROLE_CMS_ADMIN }
        - { path: ^/, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }