<?php

namespace EdcomsCMS\BadgeBundle\Entity;

/**
 * BadgeSimpleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BadgeSimpleRepository extends \Doctrine\ORM\EntityRepository
{
}
