<?php

namespace EdcomsCMS\BadgeBundle\Entity;

/**
 * BadgeAwardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BadgeAwardRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Delete all badge awards by badge
     *
     * @param $badge -
     * @return array
     */
    public function deleteByBadge(BadgeBase $badge)
    {
        $logs = $this->getEntityManager('edcoms_cms')
            ->createQuery("DELETE "
                . "FROM EdcomsCMSBadgeBundle:BadgeAward ba "
                . "WHERE ba.badge=:badge ")
            ->setParameter('badge', $badge)
            ->getResult();

        return $logs;
    }
}
