services:
    edcoms.listener.maintenance_listener:
        class: EdcomsCMS\MaintenanceBundle\EventListener\MaintenanceListener
        arguments: ["@edcoms.settings", "%edcoms.maintenance.template%", "@twig"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }