<?php
/**
 * Created by PhpStorm.
 * User: dimitris
 */

namespace EdcomsCMS\ContentBundle\Form\Type\CustomFieldData\Value;

use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\CallbackTransformer;

/**
 * Class CustomFieldDataValueChoiceType
 * @package EdcomsCMS\ContentBundle\Form\Type\CustomFieldData\Value
 */
class CustomFieldDataValueChoiceType extends ChoiceType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm( $builder, $options);
        $builder
            ->addModelTransformer(new CallbackTransformer(
                function ($value){
                    $transformedValue = json_decode($value,true);
                    return $transformedValue;
                },
                function ($value){
                    $transformedValue = json_encode($value);
                    return $transformedValue;
                }
            ))
        ;

    }

    public function getBlockPrefix()
    {
        return 'custom_field_data_value_choice_type'; // TODO: Change the autogenerated stub
    }

    public function getParent()
    {
        return 'choice';
    }
}